// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

namespace Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201123021908_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Server.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnName("Bairro")
                        .HasColumnType("text");

                    b.Property<int?>("Cep")
                        .HasColumnName("Cep")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasColumnName("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnName("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("DataNascimento")
                        .HasColumnName("DataNascimento")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnName("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnName("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnName("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnName("Sexo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
